# Generated by Django 3.0.7 on 2020-07-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheaplatzi_deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
